### ISSUE TITLE
PL or modelling language or ???

### ISSUE THREAD

**Issue by JacquesCarette** [Zistack/program-modeling-language#2]
I'm a bit confused by some of the conversation in #1. So maybe a simple question can help resolve that.  Are you:
1. trying to come up with a new PL, whose main characteristic is that of being analyzable?
2. a language for phrasing analyses certain classes of PLs?
3. two languages, one that is analyzable, and one for analyses over the first?

**Comment by Zistack** [comment]
Mostly 1.  What's going on is that it looks like there will be a core language that is directly analyzable - that is, the modelling language that I'm primarily focusing on right now - and a language that can be efficiently reduced to the core language, but includes features that make it much easier to use.

In addition to that, I'd like to formalize what representational transparency is in a way that is somewhat language-purpose agnostic, since I believe it can be generalized to other sorts of formal languages - not just ones that we would use for writing programs.  Arithmetic/calculus is a domain that I might want to fit into a representationally transparent language, for example.

**Comment by JacquesCarette** [comment]
Aha, serious progress. Ok, that question is answered, I think I'll continue this in another issue, where I ask another concrete question.
